port

diff --git a/modules/proxmox_vms/portainer-init.yml b/modules/proxmox_vms/portainer-init.yml
--- a/modules/proxmox_vms/portainer-init.yml
+++ b/modules/proxmox_vms/portainer-init.yml
@@ -26,12 +26,69 @@ write_files:
     content: |
       ${ssh_pub_key}
     permissions: 0644
-  - path: /home/core/ceph-bootstrap.sh
+  - path: /etc/systemd/system/mnt-data.mount
+    content: |
+      [Unit]
+      Description=CephFS Mount
+      After=network.target
+      Wants=network-online.target
+      Before=docker.service
+
+      [Mount]
+      What=admin@.data=/
+      Where=/mnt/data
+      Type=ceph
+
+      [Install]
+      WantedBy=multi-user.target
+  - path: /root/bootstrap/portainer-agent-stack.yml
+    content: |
+      version: '3.2'
+
+      services:
+        agent:
+          image: portainer/agent:lts
+          volumes:
+            - /var/run/docker.sock:/var/run/docker.sock
+            - /var/lib/docker/volumes:/var/lib/docker/volumes
+          networks:
+            - agent_network
+          deploy:
+            mode: global
+            placement:
+              constraints: [node.platform.os == linux]
+
+        portainer:
+          image: portainer/portainer-ce:lts
+          command: -H tcp://tasks.agent:9001 --tlsskipverify
+          ports:
+            - "9443:9443"
+            - "9000:9000"
+            - "8000:8000"
+          volumes:
+            - /mnt/data/portainer_data/:/data
+          networks:
+            - agent_network
+          deploy:
+            mode: replicated
+            replicas: 1
+            placement:
+              constraints: [node.role == manager]
+
+      networks:
+        agent_network:
+          driver: overlay
+          attachable: true
+
+  - path: /root/bootstrap/ceph-bootstrap.sh
     content: |
       #!/bin/bash
+
+      set -euo pipefail
+
       LABEL=${label}
       if [[ $LABEL =~ "bootstrap" ]]; then
-        cephadm bootstrap --mon-ip 192.168.178.100 \
+        cephadm bootstrap --mon-ip 10.0.100.1 \
           --cluster-network 10.0.100.0/24 \
           --ssh-user core \
           --fsid c739459e-16df-11f0-8000-bc2411dec559 \
@@ -43,24 +100,30 @@ write_files:
         ceph orch host add portainer-node-3 10.0.100.3 _admin
         ceph orch apply osd --all-available-devices
         ceph fs volume create data
+        ceph telemetry on --license sharing-1-0
+        ceph telemetry enable channel perf
       fi
 
-      # Sleep for OSD to complete
-      sleep 30
-      echo "* * * * * root mountpoint -q /var/lib/docker/volumes || /bin/mount -t ceph admin@.data=/ /var/lib/docker/volumes" >> /etc/crontab
+      echo "10.0.100.1,10.0.100.2,10.0.100.3:/ /mnt/data ceph name=admin,config=/etc/ceph/ceph.config,_netdev 0 2" >> /etc/fstab
+      mkdir /mnt/data
+      while ! mountpoint -q /mnt/data; do
+        echo "Mount failed or not yet mounted. Retrying in 40 seconds..."
+        /bin/mount -t ceph admin@.data=/ /mnt/data || true
+        sleep 40
+      done
+      systemctl enable mnt-data.mount
     permissions: 0755
-  - path: /home/core/swarm-bootstrap.sh
+  - path: /root/bootstrap/swarm-bootstrap.sh
     content: |
       #!/bin/bash
       LABEL=${label}
       if [[ $LABEL =~ "bootstrap" ]]; then
-        mountpoint -q /var/lib/docker/volumes || sleep 61
         docker swarm init --advertise-addr 10.0.100.1 --listen-addr 10.0.100.1
-        docker swarm join-token manager | grep "SWMTKN" > /root/swarm.sh
-        ssh -o "StrictHostKeyChecking no" -i /etc/ceph/ceph-ssh-private.key core@192.168.178.101 sudo $(cat /root/swarm.sh)
-        ssh -o "StrictHostKeyChecking no" -i /etc/ceph/ceph-ssh-private.key core@192.168.178.102 sudo $(cat /root/swarm.sh)
-        curl -L https://downloads.portainer.io/ce-lts/portainer-agent-stack.yml -o portainer-agent-stack.yml
-        docker stack deploy -c portainer-agent-stack.yml portainer
+        docker swarm join-token manager | grep "SWMTKN" > /root/bootstrap/swarm.sh
+        ssh -o "StrictHostKeyChecking no" -i /etc/ceph/ceph-ssh-private.key core@192.168.178.101 sudo $(cat /root/bootstrap/swarm.sh)
+        ssh -o "StrictHostKeyChecking no" -i /etc/ceph/ceph-ssh-private.key core@192.168.178.102 sudo $(cat /root/bootstrap/swarm.sh)
+        mkdir /mnt/data/portainer_data
+        docker stack deploy -c /root/bootstrap/portainer-agent-stack.yml portainer
       fi
     permissions: 0755
 
@@ -69,8 +132,6 @@ runcmd:
   - [systemctl, daemon-reload]
   - [systemctl, enable, --now, qemu-guest-agent]
   - [systemctl, enable, --now, docker]
-  - [bash, /home/core/ceph-bootstrap.sh]
-  - [rm, -f, /home/core/ceph-bootstrap.sh]
-  - [bash, /home/core/swarm-bootstrap.sh]
-  - [rm, -f, /home/core/swarm-bootstrap.sh]
-  - [rm, /root/swarm.sh]
+  - [bash, /root/bootstrap/ceph-bootstrap.sh]
+  - [bash, /root/bootstrap/swarm-bootstrap.sh]
+  - [rm, -r, -f, /root/bootstrap/]
